name: data-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - matplotlib
  - jupyter
  - seaborn
  - requests
  - lxml
  - beautifulsoup4
  - geopandas